In [1]:
import cv2
import numpy as np

In [18]:
face=cv2.CascadeClassifier('face.xml')
image=cv2.imread("face.jpg",1)


In [19]:
print(image)

[[[ 23  23  23]
  [ 17  17  17]
  [  8   8   8]
  ...
  [ 33  44  74]
  [ 38  49  79]
  [ 38  49  79]]

 [[ 10  10  10]
  [  8   8   8]
  [  6   6   6]
  ...
  [ 41  52  82]
  [ 42  53  83]
  [ 34  45  75]]

 [[ 11  11  11]
  [  6   6   6]
  [  5   5   5]
  ...
  [ 39  50  78]
  [ 41  52  80]
  [ 36  47  75]]

 ...

 [[  0   7   2]
  [ 10  17  12]
  [ 14  21  16]
  ...
  [ 92 117 119]
  [ 92 118 118]
  [ 95 122 119]]

 [[  2   9   6]
  [ 16  23  20]
  [ 19  26  23]
  ...
  [ 90 115 117]
  [ 87 113 113]
  [ 90 116 116]]

 [[  1   8   3]
  [ 22  29  24]
  [ 25  32  27]
  ...
  [ 91 117 117]
  [ 75 101 101]
  [ 82 109 106]]]


In [20]:
cv2.imshow('all',image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [24]:
face_only=face.detectMultiScale(image,1.15,5)

error: OpenCV(4.1.0) C:\projects\opencv-python\opencv\modules\objdetect\src\cascadedetect.cpp:1658: error: (-215:Assertion failed) !empty() in function 'cv::CascadeClassifier::detectMultiScale'


In [25]:
print(face_only)

NameError: name 'face_only' is not defined

In [ ]:
for x,w,y,h in face_only:
    cv2.rectangle(image,(x,y),(x+w,y+h),(0,0,255),2)
    cv2.imshow("facedetect, fram")